services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    hostname: nginx
    entrypoint: nginx -g "daemon off;"
    ports:
      - "8081:8081"
    networks:
      - local-network
    volumes:
      - ./nossopainel-django/staticfiles:/usr/share/nginx/html/staticfiles
      - ./nossopainel-django/mediafiles:/usr/share/nginx/html/media
    depends_on:
      - nossopainel-django
    tty: true

  nossopainel-django:
    build:
      context: ./nossopainel-django
      dockerfile: Dockerfile
    container_name: nossopainel-django
    hostname: nossopainel-django
    networks:
      - local-network
    volumes:
      - ./nossopainel-django/.env:/home/django/app/.env
      - ./nossopainel-django/database:/home/django/database
      - ./nossopainel-django/mediafiles:/home/django/app/media
      - ./nossopainel-django/db.sqlite3:/home/django/app/db.sqlite3
      - ./nossopainel-django/staticfiles:/home/django/app/staticfiles
      - ./nossopainel-django/telegram_bot.session:/home/django/app/telegram_bot.session
    ports:
       - "8001:8001"
    environment:
      - DEBUG=False
      - TZ=America/Bahia
      # Configuração MySQL
      - DB_HOST=nossopainel-mysql
      - DB_PORT=3306
      - DB_NAME=nossopaineldb
      - DB_USER=${MYSQL_USER:-nossopaineluser}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    tty: true
    restart: always
    
networks:
  local-network:
    driver: bridge
