services:

  wppconnect-server:
    build:
      context: ./wppconnect-server
      dockerfile: Dockerfile
    image: wppconnect-server
    container_name: wppconnect-server
    hostname: wppconnect-server
    entrypoint: docker-entrypoint.sh yarn dev
    networks:
      - full-network
    tty: true

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    hostname: nginx
    entrypoint: nginx -g "daemon off;"
    ports:
      - "8081:8081"
    networks:
      - full-network
    volumes:
      - ./nossopainel-django/staticfiles:/usr/share/nginx/html/staticfiles
    depends_on:
      - wppconnect-server
      - nossopainel-django
    tty: true

  nossopainel-django:
    build:
      context: ./nossopainel-django
      dockerfile: Dockerfile
    container_name: nossopainel-django
    hostname: nossopainel-django
    networks:
      - full-network
    volumes:
      - ./nossopainel-django/database:/home/django/database
      - ./nossopainel-django/staticfiles:/home/django/staticfiles
    ports:
       - "8001:8001"
    environment:
      - DEBUG=1
      - TZ=America/Bahia
    tty: true

networks:
  local-network:
    driver: bridge
