# ============================================
# MySQL Container - Nosso Painel Gestão
# SERVIDOR 1: Django + MySQL + Nginx + Certbot
# ============================================

services:

  nossopainel-mysql:
    build:
      context: ./nossopainel-mysql
      dockerfile: Dockerfile
    container_name: nossopainel-mysql
    hostname: nossopainel-mysql

    # ========================================
    # VARIÁVEIS DE AMBIENTE (use .env file)
    # ========================================
    environment:
      # Root sem senha (seguro em rede isolada internal:true)
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=nossopaineldb
      - MYSQL_USER=${MYSQL_USER:-nossopaineluser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=America/Recife
      # URL do Django para notificações WhatsApp (rede interna)
      - DJANGO_INTERNAL_URL=${DJANGO_INTERNAL_URL:-http://nossopainel-django:8001}

    # ========================================
    # REDES (APENAS INTERNA - NÃO EXPOR!)
    # ========================================
    networks:
      - database-network  # Rede interna (internal: true)

    # ========================================
    # VOLUMES PERSISTENTES
    # ========================================
    volumes:
      # Dados do MySQL (persistente)
      - ./nossopainel-mysql/data:/var/lib/mysql
      - ./nossopainel-mysql/nossopaineldb.sql:/docker-entrypoint-initdb.d/nossopaineldb.sql:ro
      
      # Backups (scripts disponíveis para configuração manual)
      - ./nossopainel-mysql/backups:/backups

      # Logs do MySQL
      - ./nossopainel-mysql/logs:/var/log/mysql

    # ========================================
    # RESTART POLICY
    # ========================================
    restart: always

    # ========================================
    # SEGURANÇA: NÃO EXPOR PORTA 3306!
    # ========================================
    # ports:
    #   - "3306:3306"
    #
    # MySQL acessível APENAS por containers na rede 'database-network'

    tty: true

# ============================================
# REDES - Segregação de acesso
# ============================================
networks:

  # Rede pública (Nginx, Django, Certbot)
  public-network:
    driver: bridge

  # Rede de banco de dados (INTERNA - MySQL + Django apenas)
  database-network:
    name: ubuntu_database-network
    driver: bridge
    internal: true
