# ============================================
# WPPConnect + Nginx - Nosso Painel Gestão
# SERVIDOR 2: WPPConnect (WhatsApp API)
# ============================================

services:

  # ==========================================
  # WPPCONNECT SERVER - WhatsApp API
  # ==========================================
  wppconnect-server:
    build:
      context: ./wppconnect-server
      dockerfile: Dockerfile
    image: wppconnect-server
    container_name: wppconnect-server
    hostname: wppconnect-server
    entrypoint: docker-entrypoint.sh yarn dev

    networks:
      - public-network

    volumes:
      - ./wppconnect-server/backups:/home/node/app/backups
      - ./wppconnect-server/tokens:/home/node/app/tokens
      - ./wppconnect-server/sessions:/home/node/app/sessions

    environment:
      - NODE_ENV=production
      - TZ=America/Recife

    tty: true
    restart: always

# ============================================
# REDES
# ============================================
networks:
  public-network:
    driver: bridge
